

/*EXCLUINDO UMA INFORMAÇÃO DO INSERT  USUARIO*/
DELETE FROM USUARIO WHERE IDUSUARIO = 2;

/* EXCLUINDO INFORMAÇÃO */ 
DECLARE @NOME VARCHAR(10) 
DECLARE @INTNOME INT 

SELECT @NOME = 'SILVIA'
SELECT @NOME

DELETE  PESSOA 
WHERE NOMEPESSOA = @NOME 


