
CREATE TABLE USUARIO (
idUSUARIO INTEGER  NOT NULL,
userUSUARIO VARCHAR(20) NOT NULL,
passUSUARIO VARCHAR(16) NOT NULL,
tipoUSUARIO NUMERIC(1) NOT NULL,
PRIMARY KEY(idUSUARIO));



SELECT * FROM USUARIO;

DROP TABLE USUARIO;  


CREATE TABLE PLANO (
idPLANO INTEGER NOT NULL ,
tipoPLANO INTEGER NOT NULL,
descPLANO VARCHAR(100) NOT NULL,
duraPLANO INTEGER NOT NULL,
valorPLANO NUMERIC(10,2) NOT NULL,
PRIMARY KEY(idPLANO));

SELECT * FROM PLANO;

CREATE TABLE USR_PLANO (
idUSR_PLANO INTEGER NOT NULL ,
idPLANO INTEGER NOT NULL,
idUSUARIO INTEGER NOT NULL,
validUSR_PLANO INTEGER NOT NULL,
PRIMARY KEY(idUSR_PLANO),
CONSTRAINT USR_PLANO_PLANO_idPLANO FOREIGN KEY (idPLANO) REFERENCES PLANO,
CONSTRAINT USR_PLANO_USUARIO_idUSUARIO FOREIGN KEY (idUSUARIO)
REFERENCES USUARIO);


SELECT * FROM USR_PLANO;

CREATE TABLE EMPRESA (
idEMPRESA INTEGER NOT NULL ,
idUSUARIO INTEGER NOT NULL,
cnpjEMPRESA NUMERIC(14) NOT NULL,
telEMPRESA NUMERIC(11) NOT NULL,
endEMPRESA VARCHAR(150) NOT NULL,
emailEMPRESA VARCHAR(100) NOT NULL,
PRIMARY KEY(idEMPRESA),
CONSTRAINT EMPRESA_USUARIO_idUSUARIO FOREIGN KEY (idUSUARIO) REFERENCES USUARIO);

SELECT * FROM EMPRESA;


CREATE TABLE PESSOA (
idPESSOA INTEGER NOT NULL ,
idUSUARIO INTEGER NOT NULL,
cpfPESSOA NUMERIC(11) NOT NULL,
telPESSOA NUMERIC(11) NOT NULL,
emailPESSOA VARCHAR(100) NOT NULL,
endPESSOA VARCHAR(150) NOT NULL,
sobrenomePESSOA VARCHAR (60) NOT NULL,
nomePESSOA VARCHAR(60) NOT NULL, 
PRIMARY KEY(idPESSOA),
CONSTRAINT PESSOA_USUARIO_idUSUARIO FOREIGN KEY (idUSUARIO) REFERENCES USUARIO);


SELECT * FROM PESSOA;





CREATE TABLE ESPECIE (
idESPECIE INTEGER NOT NULL ,
nomeESPECIE VARCHAR(50) NOT NULL,
PRIMARY KEY(idESPECIE));




SELECT * FROM  ESPECIE;

CREATE TABLE SUBESPECIE (
idSUBESPECIE INTEGER NOT NULL ,
idESPECIE INTEGER NOT NULL,
nomeSUBESPECIE VARCHAR(20) NOT NULL,
PRIMARY KEY(idSUBESPECIE),
CONSTRAINT SUBESPECIE_ESPECIE_idESPECIE FOREIGN KEY (idESPECIE) REFERENCES ESPECIE);


SELECT * FROM SUBESPECIE;

CREATE TABLE PET (
idPET INTEGER NOT NULL ,
idPESSOA INTEGER NOT NULL,
idESPECIE INTEGER NOT NULL ,
idSUBESPECIE INTEGER NOT NULL,
rgPET NUMERIC(9) NOT NULL,
obsPET VARCHAR(254) NOT NULL,
nomePET VARCHAR(30) NOT NULL,
PRIMARY KEY(idPET),
CONSTRAINT PET_ESPECIE_idESPECIE FOREIGN KEY (idESPECIE) REFERENCES ESPECIE,
CONSTRAINT PET_SUBESPECIE_idSUBESPECIE FOREIGN KEY (idSUBESPECIE) REFERENCES SUBESPECIE);

SELECT * FROM  PET;

/* A forma que o cliente vai pagar*/
CREATE TABLE PAGAMENTO (
idPAGAMENTO INTEGER NOT NULL ,
descPAGAMENTO VARCHAR(20) NOT NULL,
PRIMARY KEY(idPAGAMENTO));




SELECT * FROM  PAGAMENTO;

CREATE TABLE SERVICO (
idSERVICO INTEGER NOT NULL ,
nomeSERVICO VARCHAR(20) NOT NULL,
tipoSERVICO VARCHAR(20)  NULL, 
descSERVICO VARCHAR(50) NULL, 
PRIMARY KEY(idSERVICO));

/* ADICIONANDO COLUNAS NA TABELA SERVICO */
ALTER TABLE dbo.SERVICO ADD tipoSERVICO VARCHAR(20) NULL, descSERVICO VARCHAR(50) NULL ;

/* EXCLUINDO UMA COLUNA DA TABELA SERVICO  tipoSERVICO*/ 
ALTER TABLE dbo.SERVICO DROP COLUMN tipoSERVICO ; 


SELECT * FROM SERVICO;


CREATE TABLE SERV_EMPR (
idSERV_EMPR INTEGER NOT NULL ,
idEMPRESA INTEGER NOT NULL,
idSERVICO INTEGER NOT NULL,
vlSERV_EMPR NUMERIC(10,2) NOT NULL,
PRIMARY KEY(idSERV_EMPR),
CONSTRAINT SERV_EMPR_EMPRESA_idEMPRESA FOREIGN KEY (idEMPRESA) REFERENCES EMPRESA,
CONSTRAINT SERV_EMPR_SERVICO_idSERVICO FOREIGN KEY (idSERVICO) REFERENCES SERVICO);

SELECT * FROM SERV_EMPR;

CREATE TABLE FATURA (
  idFATURA INTEGER  NOT NULL ,
  dteFATURA DATETIME NOT NULL,
  dtvFATURA DATETIME NOT NULL,
  totFATURA NUMERIC(16,2) NOT NULL,
  vldFATURA NUMERIC(10,2) NOT NULL,
  vlpFATURA NUMERIC(16,2) NOT NULL,
  PRIMARY KEY(idFATURA),
);

SELECT * FROM  FATURA;

CREATE TABLE ITEMPEDIDO (
  idITEMPEDIDO INTEGER  NOT NULL ,
  idPEDIDO INTEGER  NOT NULL,
  itemPEDIDO VARCHAR(3) NOT NULL,
  idSERV_EMPR INTEGER  NOT NULL,
  qtdSERVICO NUMERIC(38) NOT NULL,
  vlSERVICO NUMERIC(12,2) NOT NULL,
  totSERVICO NUMERIC(14,2) NOT NULL,
  obsSERVICO VARCHAR(254) NOT NULL,
  idFATURA INTEGER NULL,
  PRIMARY KEY(idITEMPEDIDO),
  CONSTRAINT ITEMPEDIDO_PEDIDO_idPEDIDO FOREIGN KEY (idPEDIDO) REFERENCES PEDIDO,
  CONSTRAINT ITEMPEDIDO_FATURA_idFATURA FOREIGN KEY (idFATURA) REFERENCES FATURA,
  CONSTRAINT ITEMPEDIDO_SERV_EMPR_idSERV_EMPR FOREIGN KEY (idSERV_EMPR) REFERENCES SERV_EMPR
);

SELECT * FROM ITEMPEDIDO;

CREATE TABLE AVALIACAO (
  idAVALIACAO INTEGER  NOT NULL ,
  idPEDIDO INTEGER  NOT NULL,
  notaAVALIACAO FLOAT NOT NULL,
  tituloAVALIACAO VARCHAR(50) NOT NULL,
  comentAVALIACAO VARCHAR(254) NOT NULL,
  PRIMARY KEY(idAVALIACAO),
  CONSTRAINT AVALIACAO_PEDIDO_idPEDIDO FOREIGN KEY (idPEDIDO) REFERENCES PEDIDO
);

SELECT * FROM AVALIACAO

CREATE TABLE PEDIDO (
  idPEDIDO INTEGER  NOT NULL ,
  idEMPRESA INTEGER  NOT NULL,
  idPAGAMENTO INTEGER  NOT NULL,
  idPET INTEGER  NOT NULL,
  totPEDIDO NUMERIC(16,2) NOT NULL,
  PRIMARY KEY(idPEDIDO),
  CONSTRAINT PEDIDO_EMPRESA_idEMPRESA FOREIGN KEY (idEMPRESA) REFERENCES EMPRESA,
  CONSTRAINT PEDIDO_PET_idPET FOREIGN KEY (idPET) REFERENCES PET,
  CONSTRAINT PEDIDO_PAGAMENTO_idPAGAMENTO FOREIGN KEY (idPAGAMENTO) REFERENCES PAGAMENTO
);

SELECT * FROM PEDIDO;


CREATE TABLE PEDIDO_PET (
  idPEDIDO INTEGER NOT NULL,
  idPET INTEGER NOT NULL,
  PRIMARY KEY(idPEDIDO, idPET),
  CONSTRAINT PEDIDO_PET_PEDIDO_idPEDIDO FOREIGN KEY (idPEDIDO) REFERENCES PEDIDO,
   CONSTRAINT PEDIDO_PET_PET_idPET FOREIGN KEY (idPET) REFERENCES PET);

  SELECT * FROM PEDIDO_PET;


  SELECT * FROM USUARIO;
  SELECT * FROM PLANO;
  SELECT * FROM USR_PLANO;
  SELECT * FROM ESPECIE;
  SELECT * FROM SUBESPECIE;
  SELECT * FROM SERVICO;
  SELECT * FROM SERV_EMPR;
  SELECT * FROM EMPRESA;
  SELECT * FROM FATURA;
  SELECT * FROM PET;
  SELECT * FROM PEDIDO;
  SELECT * FROM PEDIDO_PET;
  SELECT * FROM ITEMPEDIDO;
  SELECT * FROM PESSOA;
  SELECT * FROM PAGAMENTO;
  SELECT * FROM AVALIACAO;









