--FAZENDO OS UPDATES
-- DE TABELAS QUE PODEM SER EDITADAS DENTRO DO CAMPO

--TABELA SUBESPECIE, COLUNA NOMESUBESPECIE 
DECLARE @NOME VARCHAR(100)  
DECLARE @ID INT


SELECT @NOME = 'NOME'
SELECT @NOME 
 
UPDATE SUBESPECIE 
SET NOMESUBESPECIE = @NOME   
WHERE IDSUBESPECIE = @ID 


--TABELA USUARIO, COLUNA PASSUSUARIO 
DECLARE @PASSUSUARIO VARCHAR(16) 
DECLARE @IDUSUARIO INT 

SELECT @PASSUSUARIO = '123456'

SELECT @PASSUSUARIO


UPDATE USUARIO
SET PASSUSUARIO = @PASSUSUARIO  
WHERE IDUSUARIO = @IDUSUARIO


--EMPRESA, COLUNA TELEFONEEMPRESA

DECLARE @TELEMPRESA VARCHAR(11) 
DECLARE @IDEMPRESA INT
 

SELECT @TELEMPRESA = '29870394'

SELECT @TELEMPRESA


UPDATE EMPRESA
SET TELEMPRESA = @TELEMPRESA  
WHERE IDEMPRESA = @IDEMPRESA

--EMPRESA, COLUNA ENDERECO 

DECLARE @ENDERECO VARCHAR(150) 
DECLARE @IDENDERECO INT
 

SELECT @ENDERECO = 'RUA: CATUMBI,  N450'

SELECT @ENDERECO


UPDATE EMPRESA
SET ENDEMPRESA = @ENDERECO  
WHERE IDEMPRESA = @IDENDERECO

--TABELA EMPRESA ,COLUNA EMAIL 

DECLARE @EMAILEMPRESA VARCHAR(110) 
DECLARE @IDEMAIL INT
 

SELECT @EMAILEMPRESA = 'IZABELSALVATI@GMAIL.COM'

SELECT @EMAILEMPRESA


UPDATE EMPRESA
SET EMAILEMPRESA = @EMAILEMPRESA  
WHERE IDEMPRESA = @IDEMAIL


-- tebela pet - coluna obspet 

DECLARE @OBSERPET VARCHAR(250) 
DECLARE @IDOBSERVPET INT 

SELECT @OBSERPET = 'ELE TEM ALERGIA, NO PELO'
SELECT @OBSERPET 


UPDATE PET 
SET OBSPET  = @OBSERPET
WHERE IDPET = @IDOBSERVPET 

					
--TABELA SUBESPECIE, COLUNA NOMESUBESPECIE
DECLARE @NOME VARCHAR(100)  
DECLARE @ID INT


SELECT @NOME = 'NOME'
SELECT @NOME 
 
UPDATE SUBESPECIE 
SET NOMESUBESPECIE = @NOME   
WHERE IDSUBESPECIE = @ID 


--TABELA USUARIO, COLUNA PASSUSUARIO
DECLARE @PASSUSUARIO VARCHAR(16) 
DECLARE @IDUSUARIO INT 

SELECT @PASSUSUARIO = '123456'

SELECT @PASSUSUARIO


UPDATE USUARIO
SET PASSUSUARIO = @PASSUSUARIO  
WHERE IDUSUARIO = @IDUSUARIO


--EMPRESA , COLUNA TELEFONEEMPRESA

DECLARE @TELEMPRESA VARCHAR(11) 
DECLARE @IDEMPRESA INT
 

SELECT @TELEMPRESA = '29870394'

SELECT @TELEMPRESA


UPDATE EMPRESA
SET TELEMPRESA = @TELEMPRESA  
WHERE IDEMPRESA = @IDEMPRESA

--EMPRESA NOME FANTASIA 

DECLARE @NMFANTASIAEMPRESA VARCHAR(100) 
DECLARE @IDFANTASIA INT
 

SELECT @NMFANTASIAEMPRESA = 'PET SHOP'

SELECT @NMFANTASIAEMPRESA


UPDATE EMPRESA

SET NFANTASIAEMPRESA = @NMFANTASIAEMPRESA  
WHERE IDEMPRESA = @IDFANTASIA


--TABELA PESSOA, COLUNA TELPESSOA

DECLARE @TELPESSOA VARCHAR(11) 
DECLARE @IDTELPESSOA INT
 

SELECT @TELPESSOA = '29870394'

SELECT @TELPESSOA


UPDATE PESSOA
SET TELPESSOA = @TELPESSOA  
WHERE IDPESSOA = @IDTELPESSOA

-- TABELA PESSOA, COLUNA EMAIL 

DECLARE @EMAILPESSOA VARCHAR(110) 
DECLARE @IDEMAILPESSOA INT
 

SELECT @EMAILPESSOA = 'MARISOLPOMA6@GMAIL.COM'

SELECT @EMAILPESSOA 


UPDATE EMPRESA
SET EMAILPESSOA = @EMAILPESSOA  
WHERE IDPESSOA = @IDEMAILPESSOA


-- TABELA PESSOA, COLUNA EDERECO 

DECLARE @ENDERECOPESSOA VARCHAR(150) 
DECLARE @IDENDERECOPESSOA INT
 

SELECT @ENDERECOPESSOA = 'Rua SILVA TELES, 500'
SELECT @ENDERECOPESSOA 


UPDATE PESSOA
SET ENDPESSOA = @ENDERECOPESSOA 
WHERE IDPESSOA = @IDENDERECOPESSOA

-- TABELA PESSOA, COLUNA NOMEPESSOA

DECLARE @NMPESSOA VARCHAR(20) 
DECLARE @IDNMPESSOA INT
 

SELECT @NMPESSOA = 'JOÃO'
SELECT @NMPESSOA 


UPDATE PESSOA
SET NOMEPESSOA = @NMPESSOA 
WHERE IDPESSOA = @IDNMPESSOA

--TABELA  PESSOA , COLUNA SOBRENOMEPESSOA

DECLARE @SOBRENMPESSOA VARCHAR(40) 
DECLARE @IDSOBRENMPESSOA INT
 

SELECT @SOBRENMPESSOA = 'SILVA DE MOURA'
SELECT @SOBRENMPESSOA 


UPDATE PESSOA
SET SOBRENOMEPESSOA= @SOBRENMPESSOA 
WHERE IDPESSOA = @IDSOBRENMPESSOA

--TABELA SERVICO, COLUNA DESCSERVICO

DECLARE @DSCSERVICO VARCHAR(100) 
DECLARE @IDDSCSERVICO INT
 

SELECT @DSCSERVICO = 'ESTE SERVIÇO SERÁ FEITO
 COM AS ORIENTAÇÕES DO VETERINÁRIO'
SELECT @DSCSERVICO 


UPDATE SERVICO
SET DESCSERVICO = @DSCSERVICO 
WHERE IDSERVICO = @IDDSCSERVICO


--TABELA SERV_EMPR, COLUNA VLSERV_EMPR
DECLARE @VALORSERV_EMPR VARCHAR(10) 
DECLARE @IDVALORSERV_EMPR INT
 

SELECT @VALORSERV_EMPR = '50'
SELECT @VALORSERV_EMPR 


UPDATE SERV_EMPR
SET VLSERV_EMPR = @VALORSERV_EMPR 
WHERE IDSERV_EMPR = @IDVALORSERV_EMPR



	SELECT * FROM USUARIO;
	SELECT * FROM PLANO;
	SELECT * FROM USR_PLANO;
	SELECT * FROM ESPECIE;
	SELECT * FROM SUBESPECIE;
	SELECT * FROM SERVICO;
	SELECT * FROM SERV_EMPR;
	SELECT * FROM EMPRESA;
	SELECT * FROM FATURA;
	SELECT * FROM PET;
	SELECT * FROM PEDIDO;
	SELECT * FROM PEDIDO_PET;
	SELECT * FROM ITEMPEDIDO;
	SELECT * FROM PESSOA;
	SELECT * FROM PAGAMENTO;
	SELECT * FROM AVALIACAO;


--TABELA PESSOA, COLUNA NOMEPESSOA 
DECLARE @NOMEPESSOA VARCHAR(10)
DECLARE @IDNOMEPESSOA INT 

SELECT @NOMEPESSOA 
SELECT @NOMEPESSOA

DELETE FROM PESSOA
WHERE IDPESSOA = 4


--TABELA SERVICO, COLUNA DESCR SERVICO 

DECLARE @DDESCSERVICO VARCHAR(100)
DECLARE @IDDESCSERVICO INT 

SELECT @DDESCSERVICO= 'ESTE SERVIÇO SEMPRE TERÁ MELHOR ATENDIMENTO' 
SELECT @DDESCSERVICO


DELETE FROM SERVICO 
WHERE IDSERVICO = 8


SELECT * FROM SERVICO;
