/* ATUALIZAÇÃO DE COLUNAS E INFORMAÇOES */ 
			UPDATE ESPECIE 
				SET NOMEESPECIE = 'AVE'
				WHERE IDESPECIE = 3

			UPDATE ESPECIE 
				SET NOMEESPECIE = 'RÉPTIL'
				WHERE IDESPECIE = 4

				
			UPDATE ESPECIE 
				SET NOMEESPECIE = 'ROEDOR'
				WHERE IDESPECIE = 5

			SELECT * FROM ESPECIE;
			SELECT * FROM SERVICO;

		/* DESC DO PLANO */
		UPDATE PLANO 
		SET DESCPLANO = 'O Estabelecimento terá seus serviços entre os primeiros da pesquisa.'
		WHERE IDPLANO = 2

		

		UPDATE USUARIO
		SET NOME = ' 

/* SELECT FROM SERVICO; */ 
SELECT * FROM USUARIO;
SELECT * FROM PLANO;
SELECT * FROM USR_PLANO;

